[tox]
envlist = py3{11,12,13}, coverage

[testenv]
deps = 
    coverage
    fixit
    ick
    libcst
    pytest
setenv =
    ICK_COVERAGE_PY=1
commands =
    ick --isolated-repo test-rules
    coverage run -m --branch --parallel pytest

[testenv:coverage]
commands =
    coverage combine -q
    coverage report -m
